name: upload-google-play-console
description: A Github action to upload abb/apk and build metadata artifacts to the Google Play Console
branding:
  color: blue
  icon: upload-cloud
inputs:
  github-token:
    description: GitHub token for authentication. Use either `secrets.GITHUB_TOKEN`, `github.token` or a personal access token.
    required: true
  service-account-credentials:
    description: The service account credentials file path. Required if GOOGLE_APPLICATION_CREDENTIALS is not set in the environment.
    required: false
  release-directory:
    description: The directory containing the APKs/AABs to upload.
    required: true
  release-name:
    description: The name of the release. Defaults to reading manifest data (version code and version string).
    required: false
  track:
    description: The track to upload the app to (e.g., `internal`, `alpha`, `beta`, `production`).
    required: false
    default: internal
  status:
    description: The status of the release. Must be one of `draft`, `inProgress`, `completed`, or `halted`.
    required: false
    default: completed
  user-fraction:
    description: Fraction of users who are eligible for a staged release. 0 < fraction < 1. Can only be set when status is `inProgress` or `halted`.
    required: false
  in-app-update-priority:
    description: In-app update priority of the release. All newly added APKs in the release will be considered at this priority. Can take values in the range [0, 5], with 5 the highest priority. Defaults to 0. `inAppUpdatePriority` can not be updated once the release is rolled out.
    required: false
  metadata:
    description: Json string or path to a JSON file that contains additional localized store listing metadata to upload. See README for details.
    required: false
  changes-not-sent-for-review:
    description: When a rejection happens, the parameter will make sure that the changes in this edit won't be reviewed until they are explicitly sent for review from within the Google Play Console UI. These changes will be added to any other changes that are not yet sent for review.
    required: false
    default: 'false'
runs:
  using: node20
  main: dist/index.js